************* Module populate_data
populate_data.py:11:0: C0301: Line too long (139/100) (line-too-long)
populate_data.py:61:0: C0301: Line too long (106/100) (line-too-long)
populate_data.py:79:0: C0301: Line too long (102/100) (line-too-long)
populate_data.py:97:0: C0301: Line too long (115/100) (line-too-long)
populate_data.py:106:0: C0301: Line too long (137/100) (line-too-long)
populate_data.py:115:0: C0301: Line too long (111/100) (line-too-long)
populate_data.py:124:0: C0301: Line too long (108/100) (line-too-long)
populate_data.py:142:0: C0301: Line too long (123/100) (line-too-long)
populate_data.py:151:0: C0301: Line too long (112/100) (line-too-long)
populate_data.py:160:0: C0301: Line too long (137/100) (line-too-long)
populate_data.py:169:0: C0301: Line too long (108/100) (line-too-long)
populate_data.py:178:0: C0301: Line too long (120/100) (line-too-long)
populate_data.py:187:0: C0301: Line too long (113/100) (line-too-long)
populate_data.py:196:0: C0301: Line too long (124/100) (line-too-long)
populate_data.py:205:0: C0301: Line too long (126/100) (line-too-long)
populate_data.py:214:0: C0301: Line too long (102/100) (line-too-long)
populate_data.py:223:0: C0301: Line too long (126/100) (line-too-long)
populate_data.py:232:0: C0301: Line too long (117/100) (line-too-long)
populate_data.py:241:0: C0301: Line too long (109/100) (line-too-long)
populate_data.py:259:0: C0301: Line too long (120/100) (line-too-long)
populate_data.py:268:0: C0301: Line too long (117/100) (line-too-long)
populate_data.py:277:0: C0301: Line too long (135/100) (line-too-long)
populate_data.py:286:0: C0301: Line too long (150/100) (line-too-long)
populate_data.py:304:0: C0301: Line too long (131/100) (line-too-long)
populate_data.py:313:0: C0301: Line too long (109/100) (line-too-long)
populate_data.py:322:0: C0301: Line too long (163/100) (line-too-long)
populate_data.py:331:0: C0301: Line too long (133/100) (line-too-long)
populate_data.py:340:0: C0301: Line too long (116/100) (line-too-long)
populate_data.py:349:0: C0301: Line too long (113/100) (line-too-long)
populate_data.py:358:0: C0301: Line too long (124/100) (line-too-long)
populate_data.py:367:0: C0301: Line too long (138/100) (line-too-long)
populate_data.py:376:0: C0301: Line too long (115/100) (line-too-long)
populate_data.py:385:0: C0301: Line too long (126/100) (line-too-long)
populate_data.py:394:0: C0301: Line too long (114/100) (line-too-long)
populate_data.py:403:0: C0301: Line too long (108/100) (line-too-long)
populate_data.py:412:0: C0301: Line too long (115/100) (line-too-long)
populate_data.py:421:0: C0301: Line too long (123/100) (line-too-long)
populate_data.py:430:0: C0301: Line too long (107/100) (line-too-long)
populate_data.py:439:0: C0301: Line too long (105/100) (line-too-long)
populate_data.py:448:0: C0301: Line too long (116/100) (line-too-long)
populate_data.py:457:0: C0301: Line too long (110/100) (line-too-long)
populate_data.py:466:0: C0301: Line too long (107/100) (line-too-long)
populate_data.py:475:0: C0301: Line too long (112/100) (line-too-long)
populate_data.py:502:0: C0301: Line too long (110/100) (line-too-long)
populate_data.py:511:0: C0301: Line too long (108/100) (line-too-long)
populate_data.py:520:0: C0301: Line too long (108/100) (line-too-long)
populate_data.py:529:0: C0301: Line too long (108/100) (line-too-long)
populate_data.py:538:0: C0301: Line too long (106/100) (line-too-long)
populate_data.py:619:0: C0301: Line too long (109/100) (line-too-long)
populate_data.py:628:0: C0301: Line too long (113/100) (line-too-long)
populate_data.py:637:0: C0301: Line too long (106/100) (line-too-long)
populate_data.py:646:0: C0301: Line too long (106/100) (line-too-long)
populate_data.py:649:9: C0303: Trailing whitespace (trailing-whitespace)
populate_data.py:655:0: C0301: Line too long (121/100) (line-too-long)
populate_data.py:664:0: C0301: Line too long (102/100) (line-too-long)
populate_data.py:682:0: C0301: Line too long (111/100) (line-too-long)
populate_data.py:691:0: C0301: Line too long (107/100) (line-too-long)
populate_data.py:728:0: C0303: Trailing whitespace (trailing-whitespace)
populate_data.py:788:28: C0303: Trailing whitespace (trailing-whitespace)
populate_data.py:812:0: C0303: Trailing whitespace (trailing-whitespace)
populate_data.py:847:0: C0301: Line too long (125/100) (line-too-long)
populate_data.py:851:0: C0301: Line too long (104/100) (line-too-long)
populate_data.py:863:0: C0301: Line too long (145/100) (line-too-long)
populate_data.py:937:0: C0301: Line too long (141/100) (line-too-long)
populate_data.py:963:0: C0301: Line too long (109/100) (line-too-long)
populate_data.py:969:0: C0301: Line too long (116/100) (line-too-long)
populate_data.py:975:0: C0301: Line too long (110/100) (line-too-long)
populate_data.py:1027:0: C0301: Line too long (135/100) (line-too-long)
populate_data.py:1111:0: C0301: Line too long (106/100) (line-too-long)
populate_data.py:1114:0: C0301: Line too long (104/100) (line-too-long)
populate_data.py:1120:0: C0301: Line too long (101/100) (line-too-long)
populate_data.py:1182:28: C0303: Trailing whitespace (trailing-whitespace)
populate_data.py:1196:0: C0301: Line too long (106/100) (line-too-long)
populate_data.py:1197:0: C0301: Line too long (116/100) (line-too-long)
populate_data.py:1221:0: C0304: Final newline missing (missing-final-newline)
populate_data.py:1:0: C0302: Too many lines in module (1221/1000) (too-many-lines)
populate_data.py:1:0: C0114: Missing module docstring (missing-module-docstring)
populate_data.py:15:0: W0404: Reimport 'SQLAlchemyError' (imported line 3) (reimported)
populate_data.py:45:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:46:4: W0621: Redefining name 'db' from outer scope (line 11) (redefined-outer-name)
populate_data.py:46:9: E0602: Undefined variable 'SessionLocal' (undefined-variable)
populate_data.py:53:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:730:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:814:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:842:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:914:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:924:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:937:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:937:0: R0914: Too many local variables (18/15) (too-many-locals)
populate_data.py:937:34: W0613: Unused argument 'users' (unused-argument)
populate_data.py:984:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:1014:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:1053:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:1091:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:1091:0: R0914: Too many local variables (19/15) (too-many-locals)
populate_data.py:1144:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:1145:37: C0121: Comparison 'Post.author == None' should be 'Post.author is None' (singleton-comparison)
populate_data.py:1147:8: W1203: Use lazy % formatting in logging functions (logging-fstring-interpolation)
populate_data.py:1150:0: C0116: Missing function or method docstring (missing-function-docstring)
populate_data.py:1209:11: W0718: Catching too general exception Exception (broad-exception-caught)
populate_data.py:1194:8: W1203: Use lazy % formatting in logging functions (logging-fstring-interpolation)
populate_data.py:1205:8: W1203: Use lazy % formatting in logging functions (logging-fstring-interpolation)
populate_data.py:1208:8: W1203: Use lazy % formatting in logging functions (logging-fstring-interpolation)
populate_data.py:1211:8: W1203: Use lazy % formatting in logging functions (logging-fstring-interpolation)
populate_data.py:1159:8: W0612: Unused variable 'group_members' (unused-variable)
populate_data.py:1165:8: W0612: Unused variable 'keywords' (unused-variable)
populate_data.py:1168:8: W0612: Unused variable 'reactions' (unused-variable)
populate_data.py:1171:8: W0612: Unused variable 'comments' (unused-variable)
populate_data.py:1174:8: W0612: Unused variable 'friendships' (unused-variable)
populate_data.py:1177:8: W0612: Unused variable 'notifications' (unused-variable)
populate_data.py:4:0: C0411: standard import "contextlib.contextmanager" should be placed before third party imports "flask.current_app", "sqlalchemy.exc.SQLAlchemyError" (wrong-import-order)
populate_data.py:6:0: C0411: standard import "logging" should be placed before third party imports "flask.current_app", "sqlalchemy.exc.SQLAlchemyError", "passlib.context.CryptContext" (wrong-import-order)
populate_data.py:7:0: C0411: standard import "hashlib" should be placed before third party imports "flask.current_app", "sqlalchemy.exc.SQLAlchemyError", "passlib.context.CryptContext" (wrong-import-order)
populate_data.py:8:0: C0411: standard import "random" should be placed before third party imports "flask.current_app", "sqlalchemy.exc.SQLAlchemyError", "passlib.context.CryptContext" (wrong-import-order)
populate_data.py:9:0: C0411: standard import "datetime.timedelta" should be placed before third party imports "flask.current_app", "sqlalchemy.exc.SQLAlchemyError", "passlib.context.CryptContext" (wrong-import-order)
populate_data.py:12:0: C0411: third party import "sqlalchemy.sql.func" should be placed before first party import "app.models.db"  (wrong-import-order)
populate_data.py:13:0: C0411: standard import "typing.List" should be placed before third party imports "flask.current_app", "sqlalchemy.exc.SQLAlchemyError", "passlib.context.CryptContext", "faker.Faker", "sqlalchemy.sql.func" and first party import "app.models.db"  (wrong-import-order)
populate_data.py:14:0: C0411: third party import "sqlalchemy.orm.Session" should be placed before first party import "app.models.db"  (wrong-import-order)
populate_data.py:15:0: C0411: third party import "sqlalchemy.exc.IntegrityError" should be placed before first party import "app.models.db"  (wrong-import-order)
populate_data.py:12:0: C0412: Imports from package sqlalchemy are not grouped (ungrouped-imports)
populate_data.py:1215:4: C0412: Imports from package app are not grouped (ungrouped-imports)
populate_data.py:2:0: W0611: Unused current_app imported from flask (unused-import)
populate_data.py:7:0: W0611: Unused import hashlib (unused-import)
populate_data.py:12:0: W0611: Unused func imported from sqlalchemy.sql (unused-import)
populate_data.py:14:0: W0611: Unused Session imported from sqlalchemy.orm (unused-import)

-----------------------------------
Your code has been rated at 5.80/10

